Cannot read property 'GCConnectionStatus_HAVE_SESSION' of undefined
joshuaferrara/node-csgo pull request #66
Opened 2019-12-04 12:00 UTC by thecatontheflat

This has resurfaced:
https://github.com/joshuaferrara/node-csgo/issues/10

2019-12-30 03:00 UTC, joshuaferrara requested changes
Thank you for your PR! Your `TODO` comment regarding the correct spot to pull the `HAVE_SESSION` is correct; I commented inline with the full path. Figured you'd probably like to make the change. Thanks again!

2019-12-30 03:00 UTC, joshuaferrara commented on index.js
> +    // TODO: This is a temporary fix since CSGO.GCConnectionStatus is undefined.
Yeah, looks like `protos.GC.CSGO.Internal.GCConnectionStatus` would be the correct spot to pull `GCConnectionStatus_HAVE_SESSION` from.

2019-12-30 22:27 UTC, thecatontheflat commented
Thanks! Updated according to the comment.

2019-12-31 02:40 UTC, joshuaferrara approved these changes

2019-12-31 03:01 UTC, merged